Fixed <p> elements with children
JacobWrenn/notus_to_html pull request #6
Opened 2020-10-15 15:53 UTC by jopicornell

I use a WYSIWYG editor on my Vue.js client, and I want my Flutter app to use Zefyr to be able to send HTML to our API. What I saw was that \<p\> HTML tags with children were not rendered correctly. If you tried to decode:
```
<p>Hello, visit <a href="https://google.com">google</a> to search through internet</p>
```
it was only encoded into a Delta document with the link.

I've changed \<p\> tag to be a block. I think it is better, because \<p\> is used to delimiter paragraphs, and in CSS they are blocks. I've done a few tests to ensure it is encoded and decoded correctly. 

Hope it helps!

2020-10-15 16:35 UTC, jopicornell commented
It has a bug, let me fix it and reopen the PR

2020-10-18 12:39 UTC, JacobWrenn commented on test/notustohtml_test.dart
> +        expect(converter.decode(html), doc.toDelta());
This is within the group of tests for encoding.

2020-10-18 12:40 UTC, JacobWrenn commented on test/notustohtml_test.dart
> +        expect(converter.decode(html), doc.toDelta());
This is within the group of tests for encoding.

2020-10-18 12:41 UTC, JacobWrenn requested changes
Hi @jopicornell thanks for identifying and fixing this. I have had a look and everything seems great. My only request for change would be in the tests you have written. Two tests for decoding have been placed within the encoding group. If you could fix this then I would be more than happy to go ahead and merge.

2020-11-03 17:25 UTC, jopicornell commented
Hi @JacobWrenn! I didn't see those comments. As there is no way to convert from delta back to a <p> element, only tests for decoding are really needed. They were duplicated, so I simply removed them from the encoding group. Hope this works for you!

2020-11-04 21:03 UTC, merged

2020-11-04 21:03 UTC, JacobWrenn commented
Sounds good to me. I'll get this published.